### PR TITLE
Design changes 

### PR DESCRIPTION
**Pull request by Thilagavathi1**
Please check this PR

### CODE REVIEW

**Comment by TG1999** [comment]
Please can you describe your changes and send a screenshot of the changes you made

**Comment by Thilagavathi1** [comment]
issueTracker
Please check this. Shall i change the color code for the issue card background?

**Comment by TG1999** [comment]
Cc @lakshyabatman

**Comment by Thilagavathi1** [comment]
@lakshyabatman Any updates on this PR!

**Pull request merged**
